services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROJECT_DIR=${PROJECT_DIR}
    restart: unless-stopped
    ports:
      - '${APP_PORT}:${APP_PORT}'
    env_file:
      - .env
      - .env.production
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - hono_starter_net
    volumes:
      - logs:${PROJECT_DIR}/logs
    
  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
      - .env.production
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=Asia/Shanghai
    networks:
      - hono_starter_net
    healthcheck:
      test: [CMD-SHELL, "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  logs:

networks:
  hono_starter_net:
    name: hono_starter_net
